import os
import json
import openai

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
openai.api_key = OPENAI_API_KEY

def narrate_lesson_moments(lesson_data: dict) -> dict:
    """
    Takes the structured moments generated by Lesson Director (with empty 'say' strings)
    and uses the LLM purely to write the conversational Russian script for each step.
    Returns the fully populated lesson_data.
    """
    
    system_prompt = """You are a Go (Weiqi / Baduk) coach. 
We have already built the exact pedagogical structure and visual actions (arrows, highlights) for a lesson moment. 
Your ONLY job is to write the spoken Russian commentary ("say" field) for each step in the provided JSON.

CRITICAL RULES:
1. You MUST NOT change the length of the steps array, nor alter the "actions" or any other metadata.
2. Produce only a JSON object mapping step IDs to their "say" text. 
3. The tone must be helpful, encouraging, and clear. Language: Russian.
4. Keep the text closely tied to the "actions" and "teachingGoal" of the step. For example, if the action highlights an urgent group, talk about the urgent group.
5. If the step shows a ghost sequence or best play, describe WHY it works based on the context provided.
6. The user is referred to generally, or you can use "вы" (you).
7. Speak like a human teacher showing variations on a board.

Respond EXACTLY with valid JSON in this format:
{
  "step_id_1": "Текст для первого шага...",
  "step_id_2": "Текст для второго шага..."
}
"""

    for moment in lesson_data.get("moments", []):
        # We process one moment at a time to keep LLM context focused
        user_prompt = f"Moment Metadata:\nTitle: {moment.get('title')}\nGoal: {moment.get('teachingGoal')}\n"
        user_prompt += f"Summary: {json.dumps(moment.get('teachingPackSummary', {}), ensure_ascii=False)}\n\n"
        user_prompt += "Steps needing voiceover:\n"
        
        for step in moment.get("steps", []):
            user_prompt += f"Step ID: {step['id']}\nActions: {json.dumps(step.get('actions', []), ensure_ascii=False)}\n\n"
            
        try:
            response = openai.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.4,
                response_format={"type": "json_object"}
            )
            
            content = response.choices[0].message.content
            say_dict = json.loads(content)
            
            # Populate the original steps
            for step in moment.get("steps", []):
                step_id = step["id"]
                if step_id in say_dict:
                    step["say"] = say_dict[step_id]
                else:
                    step["say"] = "Ошибка генерации текста для этого шага."
                    
        except Exception as e:
            print(f"Error generating narration for moment {moment.get('moment_id')}: {e}")
            for step in moment.get("steps", []):
                step["say"] = "Произошла ошибка при генерации озвучки."

    return lesson_data
