import os
import json
from typing import List, Dict, Any

class MarkdownGenerator:
    def __init__(self, site_dir: str, site_name: str, base_url: str):
        self.site_dir = site_dir
        self.site_name = site_name
        self.base_url = base_url
        self.md_path = os.path.join(site_dir, "site_crawling.md")
        
        self.screens = []
        self.features = []
        
        # Load existing if any
        self._load_existing_data()

    def _load_existing_data(self):
        # We would probably fetch this from Orchestrator API, 
        # but as a stateless worker we can also build up the local cache if we had one.
        pass

    def init_document_if_empty(self):
        if not os.path.exists(self.md_path):
            content = f"""# Crawler Report: {self.site_name}
**Base URL:** {self.base_url}

## 1. Общая информация о сайте
(Auto-generated by Crawler)

## 2. Карта экранов
<!-- SCANNER: SCREENS_START -->
<!-- SCANNER: SCREENS_END -->

## 3. Список найденных фич
<!-- SCANNER: FEATURES_START -->
<!-- SCANNER: FEATURES_END -->

## 4. Поведенческие паттерны
## 5. Игровые сценарии
## 6. Что ещё не изучено
"""
            with open(self.md_path, "w", encoding="utf-8") as f:
                f.write(content)

    def add_screen(self, screen_id: str, title: str, url: str, screenshot: str, elements: List[Dict]):
        # Temporary logic for MVP file saving
        self.screens.append({
            "id": screen_id,
            "title": title,
            "url": url,
            "screenshot": screenshot,
            "element_count": len(elements)
        })
        
        self._rewrite_markdown()

    def add_feature(self, feature_id: str, name: str, screen: str, f_type: str, action: str):
        self.features.append({
            "id": feature_id,
            "name": name,
            "screen": screen,
            "type": f_type,
            "action": action
        })
        self._rewrite_markdown()

    def _rewrite_markdown(self):
        if not os.path.exists(self.md_path):
            self.init_document_if_empty()
            
        with open(self.md_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Update screens block
        screen_text = ""
        for s in self.screens:
            screen_text += f"\n### {s['id']}: {s['title']}\n"
            screen_text += f"- **URL**: {s['url']}\n"
            screen_text += f"- **Interactive Elements**: {s['element_count']}\n"
            screen_text += f"- **Screenshot**: [Link]({s['screenshot']})\n"

        # Naive replacement
        import re
        content = re.sub(
            r"(<!-- SCANNER: SCREENS_START -->).*?(<!-- SCANNER: SCREENS_END -->)",
            fr"\1\n{screen_text}\n\2",
            content,
            flags=re.DOTALL
        )

        feature_text = ""
        for f in self.features:
            feature_text += f"\n#### Feature {f['id']}\n"
            feature_text += f"**Название**: {f['name']}\n"
            feature_text += f"**Экран**: {f['screen']}\n"
            feature_text += f"**Тип**: {f['type']}\n"
            feature_text += f"**Действие**: {f['action']}\n"
            feature_text += f"**Статус**: Unconfirmed\n"

        content = re.sub(
            r"(<!-- SCANNER: FEATURES_START -->).*?(<!-- SCANNER: FEATURES_END -->)",
            fr"\1\n{feature_text}\n\2",
            content,
            flags=re.DOTALL
        )

        with open(self.md_path, "w", encoding="utf-8") as f:
            f.write(content)
